version: '3'

services:

  nginx:
    container_name: nginx-server
    image: nginx:stable
    restart: always
    ports:
      - 9000:80
    working_dir: /usr/share/nginx/html
    volumes:
      - ./:/usr/share/nginx/html
